spring.application.name=api

# MySQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# JWT config
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-expiration-minutes=15
app.security.jwt.refresh-expiration-days=30
app.security.jwt.issuer=${JWT_ISSUER}

# CORS front-end origin
app.frontend.url=${WEB_URL}

