spring:
  application:
    name: api
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false

app:
  frontend:
    origin: ${WEB_URL}
  security:
    jwt:
      issuer: ${JWT_ISSUER:self}
      expiration-minutes: ${ACCESS_EXP:15}
      private: ${JWT_PRIVATE}
      public: ${JWT_PUBLIC}
    refresh:
      expiration-days: ${REFRESH_EXP:30}
